# Generated by Django 4.1.3 on 2022-12-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allemployees',
            name='dct',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allemployees',
            name='calendar',
            field=models.ManyToManyField(blank=True, null=True, to='main.calendar'),
        ),
    ]
