# Generated by Django 4.1.3 on 2022-12-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allemployees',
            name='ruc',
            field=models.CharField(default=1, max_length=100, verbose_name='Руководитель'),
            preserve_default=False,
        ),
    ]
