# Generated by Django 4.1.3 on 2022-12-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allemployees_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployees',
            name='ruc',
            field=models.CharField(max_length=100, verbose_name='Рук'),
        ),
    ]
