# Generated by Django 4.1.3 on 2022-12-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allemployees_dct_alter_allemployees_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployees',
            name='dct',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
