# Generated by Django 4.1.3 on 2022-12-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_allemployees_ruc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allemployees',
            name='ruc',
        ),
    ]
