# Generated by Django 4.1.3 on 2022-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_allemployees_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployees',
            name='ruc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
