# Generated by Django 4.1.3 on 2022-12-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_allemployees_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allemployees',
            name='ruc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.allemployees', verbose_name='Руководитель'),
        ),
    ]
