# Generated by Django 4.1.3 on 2022-12-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_allemployees_ruc_allemployees_rucod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allemployees',
            name='rucod',
        ),
    ]
