# Generated by Django 4.1.3 on 2022-12-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_allemployees_rucod'),
    ]

    operations = [
        migrations.AddField(
            model_name='allemployees',
            name='rucod',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
